spring.application.name=hotel_booking

server.port=1011

spring.datasource.url=jdbc:mysql://localhost:3306/hotelv3
spring.datasource.username=root
spring.datasource.password=rabbi1067

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
